#名称加上dev，表示实验版本，即这个文件中的属性是为了方便测试环节使用，实际开发时可能还会变

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id:
#    access-key-secret:
    bucket-name: herohaoyu
  redis:
    host: localhost
    port: 6379
    password: '123456'
    database: 10

